- name: install the latest version of nfs-utils
  dnf:
    name: nfs-utils
    state: latest
  become: yes
- name: install the latest version of net-tools
  dnf:
    name: net-tools
    state: latest
  become: yes
- name: enable service nfs-server
  systemd:
    name: nfs-server
    enabled: yes
  become: yes
- name: make sure nfs-server service is running
  systemd:
    state: started
    name: nfs-server
  become: yes