- name: set timezone to Europe/Madrid
  community.general.timezone:
    name: Europe/Madrid
  become: yes
- name: install the latest version of chrony
  dnf:
    name: chrony
    state: latest
  become: yes
- name: enable chrony service
  systemd:
    name: chronyd
    enabled: yes
  become: yes
- name: make sure chrony service is running
  systemd:
    state: started
    name: chronyd
  become: yes
- name: enable set-ntp
  command: timedatectl set-ntp true
  become: yes
