- name: install container
  command: kubeadm init --pod-network-cidr 192.169.0.0/16 --ignore-preflight-errors=all
  register: add_worker_command
  become: yes
- name: copy to local file
  local_action: copy content={{ add_worker_command }} dest=output.txt
- name: copy to local file
  local_action: copy content={{ add_worker_command.stdout_lines[-2:] }} dest=output-simple.txt
# - name: command to add workers in future
#   debug:
#     msg: {{ init_output.stdout_lines[-2] }} {{ init_output.stdout_lines[-1] }}
- name: create .kube folder 
  command: mkdir -p /root/.kube
  become: yes
- name: copy admin.conf to kube config
  command: cp -i /etc/kubernetes/admin.conf /root/.kube/config
  become: yes